modLoader="javafml"
loaderVersion="[47,)"
license="Public Domain"

[[mods]]
modId="trueheal"
version="1.0.0"
displayName="True Healing"
updateJSONURL="https://github.com/DRAKKKS/True-Healing/blob/master/update.json"
displayURL="https://github.com/DRAKKKS/True-Healing.git"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Drakkks, MCreator"
description="Mobs heal after they're hurt using a custom potion effect."

[[dependencies.trueheal]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"

[[dependencies.trueheal]]
    modId="forge"
    mandatory=true
    versionRange="[47.2.0]"
    ordering="NONE"
    side="BOTH"



